=begin

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

=end

def count_divisors(number)
  divisors = 0
  number_sqrt = Math.sqrt(number)
  for i in (1..number_sqrt)
    if number % i == 0
      divisors += 2
    end
  end
  if number_sqrt % 1 == 0
    divisors -=1
  end

  return divisors
end

triangle_number = 0
back_row = 1
begin
  triangle_number += back_row
  back_row += 1
  divisors = count_divisors(triangle_number)
  puts divisors
end while divisors < 500

puts triangle_number
